from __future__ import annotations

from copy import deepcopy
from typing import Any


# Research defaults only. Brokers and exchanges can change margin schedules and fees,
# so callers should persist the exact contract snapshot used for every audit.
CONTRACT_CATALOG: dict[str, dict[str, Any]] = {
    "CME:ES": {
        "symbol": "ES",
        "venue": "CME",
        "instrument_type": "listed_future",
        "contract_multiplier": 50,
        "tick_size": 0.25,
        "quantity_step": 1,
        "minimum_quantity": 1,
        "initial_margin_rate": 0.10,
        "maintenance_margin_rate": 0.08,
        "maximum_leverage": 20,
    },
    "CME:MES": {
        "symbol": "MES",
        "venue": "CME",
        "instrument_type": "listed_future",
        "contract_multiplier": 5,
        "tick_size": 0.25,
        "quantity_step": 1,
        "minimum_quantity": 1,
        "initial_margin_rate": 0.10,
        "maintenance_margin_rate": 0.08,
        "maximum_leverage": 20,
    },
    "CME:NQ": {
        "symbol": "NQ",
        "venue": "CME",
        "instrument_type": "listed_future",
        "contract_multiplier": 20,
        "tick_size": 0.25,
        "quantity_step": 1,
        "minimum_quantity": 1,
        "initial_margin_rate": 0.10,
        "maintenance_margin_rate": 0.08,
        "maximum_leverage": 20,
    },
    "CME:MNQ": {
        "symbol": "MNQ",
        "venue": "CME",
        "instrument_type": "listed_future",
        "contract_multiplier": 2,
        "tick_size": 0.25,
        "quantity_step": 1,
        "minimum_quantity": 1,
        "initial_margin_rate": 0.10,
        "maintenance_margin_rate": 0.08,
        "maximum_leverage": 20,
    },
    "CME:CL": {
        "symbol": "CL",
        "venue": "NYMEX",
        "instrument_type": "listed_future",
        "contract_multiplier": 1000,
        "tick_size": 0.01,
        "quantity_step": 1,
        "minimum_quantity": 1,
        "initial_margin_rate": 0.12,
        "maintenance_margin_rate": 0.10,
        "maximum_leverage": 15,
    },
    "CME:MCL": {
        "symbol": "MCL",
        "venue": "NYMEX",
        "instrument_type": "listed_future",
        "contract_multiplier": 100,
        "tick_size": 0.01,
        "quantity_step": 1,
        "minimum_quantity": 1,
        "initial_margin_rate": 0.12,
        "maintenance_margin_rate": 0.10,
        "maximum_leverage": 15,
    },
    "BINANCE:BTCUSDT": {
        "symbol": "BTCUSDT",
        "venue": "BINANCE",
        "instrument_type": "crypto_perpetual",
        "contract_multiplier": 1,
        "tick_size": 0.1,
        "quantity_step": 0.001,
        "minimum_quantity": 0.001,
        "initial_margin_rate": 0.02,
        "maintenance_margin_rate": 0.005,
        "maximum_leverage": 50,
    },
    "BYBIT:BTCUSDT": {
        "symbol": "BTCUSDT",
        "venue": "BYBIT",
        "instrument_type": "crypto_perpetual",
        "contract_multiplier": 1,
        "tick_size": 0.1,
        "quantity_step": 0.001,
        "minimum_quantity": 0.001,
        "initial_margin_rate": 0.02,
        "maintenance_margin_rate": 0.005,
        "maximum_leverage": 50,
    },
    "BITUNIX:BTCUSDT": {
        "symbol": "BTCUSDT",
        "venue": "BITUNIX",
        "instrument_type": "crypto_perpetual",
        "contract_multiplier": 1,
        "tick_size": 0.1,
        "quantity_step": 0.001,
        "minimum_quantity": 0.001,
        "initial_margin_rate": 0.02,
        "maintenance_margin_rate": 0.005,
        "maximum_leverage": 50,
    },
}


def contract_catalog() -> dict[str, dict[str, Any]]:
    return deepcopy(CONTRACT_CATALOG)
